/**
 * TypeScript SDK client for legal hallucination detection API.
 *
 * Types are auto-generated from OpenAPI schema via openapi-sync.sh.
 * Do not edit generated types manually — regenerate when schemas change.
 *
 * Usage:
 *   import { HallucinationDetectorClient } from './client';
 *   const client = new HallucinationDetectorClient('http://localhost:8000/api');
 *   const response = await client.check({ text: 'Section 43A...' });
 *   console.log(response.decision);
 */

// Import types from generated OpenAPI types
// These are auto-generated by openapi-sync.sh and should not be edited manually
import type { CheckResponse, CheckRequest, AnalyticsSummary } from './generated-types';

export class DetectorAPIError extends Error {
  constructor(
    public statusCode: number,
    public detail: string,
    public responseText?: string,
  ) {
    super(`API Error ${statusCode}: ${detail}`);
    this.name = 'DetectorAPIError';
  }
}

export interface ChecksListResponse {
  total: number;
  checks: Array<{
    request_id: string;
    trust_index: number;
    decision: string;
    created_at: string;
  }>;
}

export interface FlaggedListResponse {
  total: number;
  flagged_checks: Array<{
    request_id: string;
    trust_index: number;
    decision: string;
    created_at: string;
  }>;
}

export class HallucinationDetectorClient {
  /**
   * Initialize the client.
   *
   * @param baseUrl - Base URL of the API endpoint (e.g., 'http://localhost:8000/api')
   */
  constructor(private baseUrl: string) {
    this.baseUrl = baseUrl.replace(/\/$/, ''); // Remove trailing slash
  }

  /**
   * Check LLM output for hallucinations.
   *
   * @param request - CheckRequest with text and optional context
   * @returns CheckResponse with claims, verdicts, trust_index, decision
   * @throws DetectorAPIError on non-OK response
   */
  async check(request: CheckRequest): Promise<CheckResponse> {
    try {
      const response = await fetch(`${this.baseUrl}/check`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(request),
      });

      if (!response.ok) {
        const detail = await response.text();
        throw new DetectorAPIError(response.status, detail, detail);
      }

      return (await response.json()) as CheckResponse;
    } catch (error) {
      if (error instanceof DetectorAPIError) {
        throw error;
      }
      throw new DetectorAPIError(
        0,
        `Request failed: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /**
   * Get aggregate analytics summary.
   *
   * @param days - Number of days to look back (default: 30)
   * @returns Summary with total_checks, avg_trust_index, etc.
   * @throws DetectorAPIError on non-OK response
   */
  async getSummary(days = 30): Promise<AnalyticsSummary> {
    try {
      const response = await fetch(
        `${this.baseUrl}/analytics/summary?days=${days}`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );

      if (!response.ok) {
        const detail = await response.text();
        throw new DetectorAPIError(response.status, detail, detail);
      }

      return (await response.json()) as AnalyticsSummary;
    } catch (error) {
      if (error instanceof DetectorAPIError) {
        throw error;
      }
      throw new DetectorAPIError(
        0,
        `Request failed: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /**
   * Get paginated list of recent checks.
   *
   * @param limit - Max results per page (default: 50)
   * @param offset - Pagination offset (default: 0)
   * @returns List of checks with metadata
   * @throws DetectorAPIError on non-OK response
   */
  async getChecks(limit = 50, offset = 0): Promise<ChecksListResponse> {
    try {
      const response = await fetch(
        `${this.baseUrl}/analytics/checks?limit=${limit}&offset=${offset}`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );

      if (!response.ok) {
        const detail = await response.text();
        throw new DetectorAPIError(response.status, detail, detail);
      }

      return (await response.json()) as ChecksListResponse;
    } catch (error) {
      if (error instanceof DetectorAPIError) {
        throw error;
      }
      throw new DetectorAPIError(
        0,
        `Request failed: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /**
   * Get paginated list of flagged checks (for review).
   *
   * @param limit - Max results per page (default: 50)
   * @param offset - Pagination offset (default: 0)
   * @returns List of flagged checks with metadata
   * @throws DetectorAPIError on non-OK response
   */
  async getFlagged(limit = 50, offset = 0): Promise<FlaggedListResponse> {
    try {
      const response = await fetch(
        `${this.baseUrl}/analytics/flagged?limit=${limit}&offset=${offset}`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );

      if (!response.ok) {
        const detail = await response.text();
        throw new DetectorAPIError(response.status, detail, detail);
      }

      return (await response.json()) as FlaggedListResponse;
    } catch (error) {
      if (error instanceof DetectorAPIError) {
        throw error;
      }
      throw new DetectorAPIError(
        0,
        `Request failed: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }
}
